spring.application.name=StudentManagementSystemBackend
spring.datasource.url=jdbc:mysql://localhost:3306/exp12_db
spring.datasource.username=root
spring.datasource.password=Nishipriya@3113

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true